NAME     = 'server'
NETWORK  = '172.27.11.'
PACKAGES = 'curl wget vim'


Vagrant.configure("2") do |config|
  config.vm.define "#{NAME}1" do |server1|
    server1.vm.box = "centos/7"
    server1.vm.network "private_network", ip: NETWORK + "10"
    server1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end
    server1.vm.provision "shell", inline: <<-SHELL
      yum install -y httpd #{PACKAGES}
      yum install -y python3
      yum update
      yum upgrade
      systemctl enable httpd
      systemctl start httpd
    SHELL
  end
  config.vm.define "#{NAME}2" do |server2|
   server2.vm.box = "debian/buster64"
   server2.vm.network "private_network", ip: NETWORK + "20"
   server2.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = "2"
  end
  server2.vm.provision "shell", inline: <<-SHELL
    apt-get update #{PACKAGES}
    apt-get upgrade
    apt-get install -y apache2
    apt-get install -y python3
  SHELL
end
  config.vm.provision "shell", inline: <<-SHELL
    id devops
    if [ "$?" -ne 0 ]; then
      useradd -m -d /home/devops -s /bin/bash devops
    fi  
  SHELL
end


